services:
  postgres:
    image: postgres:18
    env_file: .env.local
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: open_cinema_local
      POSTGRES_DB: open_cinema
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql
  redis:
    image: redis:8.6.3
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping | grep PONG"]
      interval: 1s
      timeout: 3s
      retries: 5
    command: ["redis-server"]
  rustfs:
    image: rustfs/rustfs:latest
    environment:
      RUSTFS_ACCESS_KEY: rustfsadmin
      RUSTFS_SECRET_KEY: rustfsadmin
    ports:
      - 9000:9000
      - 9001:9001
    volumes:
      - rustfs_data:/data

volumes:
  postgres_data:
  rustfs_data:
