services:
  postgres:
    image: postgres:18
    env_file: .env.local
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: open_cinema_local
      POSTGRES_DB: open_cinema
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql

volumes:
  postgres_data:
